{{- if (include "identity-manager.formrenderer.deploy" .) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-manager.formrenderer.name" . }}
  labels:
    {{- include "identity-manager.formrenderer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.formrenderer.autoscaling.enabled }}
  replicas: {{ .Values.formrenderer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "identity-manager.formrenderer.selectorLabels" . | nindent 6 }} 
  template:
    metadata:
      {{- with .Values.formrenderer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "identity-manager.formrenderer.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "identity-manager.imagePullSecrets" . | nindent 8 }}
      serviceAccountName: {{ include "identity-manager.formrenderer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.formrenderer.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-formrenderer
        
          image: {{ include "identity-manager.identityutils.image" . | quote }}
          imagePullPolicy: {{ include "identity-manager.imagePullPolicy" . | quote }}

          env:

            {{- include "identity-manager.configuration.envs" 
            (dict
              "top" .
            ) | nindent 12 }}

          command:
              - "/bin/bash"
              - "-c"
              - >

                {{ include "identity-manager.generate-secret-properties.command" 
                (dict 
                  "top" . 
                  "secretMountFolder" "/mnt/secrets-store" 
                  "secretPropertiesPath" "/shared-conf/secret.properties"
                ) | nindent 16 }}

                {{ include "identity-manager.add-keystore-pwd-to-secret-properties.command" 
                (dict 
                  "top" .
                  "secretMountFolder" "/mnt/key-store-pwd" 
                  "secretPropertiesPath" "/shared-conf/secret.properties"
                ) | nindent 16 }}
          
          volumeMounts:
          
            {{- include "identity-manager.secrets.volumeMount" 
            (dict 
              "top" . 
              "mountPath" "/mnt/secrets-store"
            ) | nindent 12 }}

            {{- include "identity-manager.key-store-pwd.volumeMount" 
            (dict 
              "top" .
              "mountPath" "/mnt/key-store-pwd"
            ) | nindent 12 }}
 
            {{- include "identity-manager.shared.volumeMount" 
            (dict 
              "volumeName" "shared-conf" 
              "mountPath" "/shared-conf"
            ) | nindent 12 }}

      containers:
        - name: {{ include "identity-manager.formrenderer.name" . }}
          securityContext:
            {{- toYaml .Values.formrenderer.securityContext | nindent 12 }}
          image: {{ include "identity-manager.formrenderer.image" . | quote }}
          imagePullPolicy: {{ include "identity-manager.imagePullPolicy" . | quote }}

          env:

            {{- include "identity-manager.configuration.envs" 
            (dict
              "top" .
            ) | nindent 12 }}

            - name: SECRET_PROPERTY_PATH
              value: /shared-conf/secret.properties
              
          ports:
            - name: http
              containerPort: {{ .Values.formrenderer.service.ports.httpPort }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          readinessProbe:
            exec:
              command:
              - cat 
              - /opt/netiq/idm/apps/sites/config.ini
            failureThreshold: 180
            periodSeconds: 10
          resources:
            {{- toYaml .Values.formrenderer.resources | nindent 12 }}
          volumeMounts:

            {{- include "identity-manager.shared-persistent.volumeMount" 
            (dict
              "mountPath" "/config"
            ) | nindent 12 }}

            {{- include "identity-manager.shared.volumeMount" 
            (dict 
              "volumeName" "shared-conf" 
              "mountPath" "/shared-conf"
            ) | nindent 12 }}
            
      volumes:

        {{- include "identity-manager.shared-persistent.volume" 
        (dict
          "top" .
        ) | nindent 8 }}
        
        {{- include "identity-manager.secrets.volume" 
        (dict
          "top" .
        ) | nindent 8 }}
        

        {{- include "identity-manager.key-store-pwd.volume" 
        (dict
          "top" .
        ) | nindent 8 }}
        
        {{- include "identity-manager.shared.volume" 
        (dict 
          "name" "shared-conf"
        ) | nindent 8 }}
        
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.formrenderer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.formrenderer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.formrenderer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
