{{- if (include "identity-manager.formrenderer.deploy" .) }}

{{- if .Values.formrenderer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.formrenderer.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.formrenderer.labels" . | nindent 4 }}
  {{- with .Values.formrenderer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 

{{- end }}
