---
# tasks file for common


#- name: "Stop Firewalld in Target hosts - SLES Servers"
#  service:
#    name: SuSEfirewall2
#    state: stopped
#  notify: stop_firewall_sles
#  when: ansible_distribution == "SLES"
#  tags: stop_firewall

- name : Print current working directory
  debug :
    msg : "{{ playbook_dir }}"

#- name: "Convert Silent Property file to Yaml file"
#  shell: |
#    #cd "{{ playbook_dir }}/variables/"
#    sh -x variables/files/convertsilentprop2yaml.sh
#  notify: handler_for_message - convert_property2yaml
#  delegate_to: localhost


- name : Load conf.yml
  include_vars : "{{ playbook_dir }}/common/conf/conf.yml"

- name : Load main.yml
  include_vars : files/main.yml
  
 
  


