---
# tasks file for activemq

- name : Get ActiveMQ image file stats
  local_action: stat path="{{ images_dir }}//docker-images/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_activemq.tar.gz"
  register: amqfile

- name : Check for image existence in Docker host
  shell : docker images | grep activemq | grep {{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}
  register : imagealreadyloaded
  ignore_errors : yes
  
- name : Print shared volume location
  debug :
    msg : "{{ activemq_shared_volume }}"
    
- name: Create "{{ activemq_shared_volume }}" if it does not exist
  file:
    path: "{{ activemq_shared_volume }}"
    state: directory
    mode: 0775

- name : Copy the ActiveMQ image to Docker host
  copy :
          src : "{{ images_dir }}//docker-images/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_activemq.tar.gz"
          dest : "{{ activemq_shared_volume }}"
  when : 
        - amqfile.stat.exists
        - imagealreadyloaded.rc == 1


- name : Load the ActiveMQ image
  docker_image:
    state : present
    name: activemq:idm-{{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}
    load_path: "{{ activemq_shared_volume }}/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_activemq.tar.gz"
    timeout: 3000
    source: load
#  notify : Load activemq Image
  when : imagealreadyloaded.rc == 1
  
- name : Copy silent.properties file to target server
  template :
    src : "silent.properties"
    dest : "{{ activemq_shared_volume }}" 
    
- name : Copy ActiveMQ files to shared volume
  copy :
    src : "{{ role_path }}/files/{{ item }}"
    dest : "{{ activemq_shared_volume }}"
  loop: "{{ activemq_files }}"
  when: activemq_files is defined

- name : Deploy ActiveMQ container
  docker_container :
    name : "{{ activemq_container_name }}"
    image : "activemq:idm-{{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}"
    state: started
    stop_timeout: 300
    hostname : "{{ activemq_container_hostname }}"
    network_mode : "{{ network_set }}"
    networks :
      - name : "{{ network_set }}"
#        ipv4_address : "{{ activemq_container_ipaddress }}"
    volumes : "{{ activemq_volumes | default([]) }}"
    ports : "{{ activemq_port_mapping | default([]) }}"
#    dns_servers : "{{ dns_list | default([]) }}"
    env_file: "{{ activemq_shared_volume }}/silent.properties"
  tags : deploy_amq_container
#  notify : Deploy activemq Container

- name : Delete ActiveMQ tarball
  file :
          path : "{{ activemq_shared_volume }}/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_activemq.tar.gz"
          state : absent
          
- name: Delete silent.properties file
  file:
    path: "{{ activemq_shared_volume }}/silent.properties"
    state: absent
