rm /opt/novell/eDirectory/lib/dirxml/classes/mapdb-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/lz4-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/lucene-core-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/leveldbjni-all-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/kotlin-stdlib-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/kotlin-runtime-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jsr311-api-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jetty-all-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jersey-bundle-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-module-jaxb-annotations-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-mapper-asl-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-jaxrs-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-dataformat-xml-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-databind-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-core-asl-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-core-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/jackson-annotations-*jar
rm /opt/novell/eDirectory/lib/dirxml/classes/guava-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/eclipse-collections-api-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/eclipse-collections-forkjoin-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/eclipse-collections-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/elsa-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/aalto-xml-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/commons-lang*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/commons-io-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/httpclient-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/httpcore-*.jar
rm /opt/novell/eDirectory/lib/dirxml/classes/opencsv-*.jar