---
# tasks file for bvt_foa
    - name: "Add nds user to Remote VM"
      shell: useradd -p $(openssl passwd -crypt 'novell') -u 35753 -m nds
      ignore_errors: yes

    - name: "Create Automation Directory for BVT"
      file:
          path: "{{ fanoutagent_shared_volume }}/Automation"
          state: directory
          mode: '644'
          
    - name: "Copy Version Check script to Automation Directory"
      template:
           src: "bvt_foa.sh"
           dest: "{{ fanoutagent_shared_volume }}/Automation"
           owner: root
           group: root
           mode: '777'
           
    - name: "Assign permissions to Automation Directory"
      shell: chown -R 35753:root {{ fanoutagent_shared_volume }}/Automation
           
    - name: "Creates results Directory"
      file:
        path: "{{ playbook_dir}}/results_bvt"
        state: directory
        mode: '644'
      delegate_to: localhost
        
#    - name: "Run Version Check Script on BVT IDM FOA"
#      shell: "docker exec -it engine-container su nds /config/Automation/bvt_foa.sh"        
#      args:
#        chdir: "/data/Automation"
        
    - name: "Install unzip"
      community.docker.docker_container_exec:
        container: foa-container
        command: zypper --non-interactive install unzip

    - name: "Run Version Check Script on BVT IDM FOA"
      community.docker.docker_container_exec:
        container: foa-container
        command: sh bvt_foa.sh
        chdir: /config/Automation/
 
    - name: "Fetch log files from BVT IDM FOA Server to Ansible Controller"
      fetch:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/results_bvt/"
        flat: yes
      with_items:
             - "{{ fanoutagent_shared_volume }}/Automation/result"
             - "{{ fanoutagent_shared_volume }}/Automation/foa.html"
             - "{{ fanoutagent_shared_volume }}/Automation/bvt_result"
             
    - name: "Read version check results"
      shell: |
          cat "{{ playbook_dir }}/results_bvt/result"
      register: results
      delegate_to: localhost
      
    - name: "Generate FanOut jars version check html report"
      shell: |
          cd "{{ playbook_dir }}/results_bvt"
          cat ./../roles/bvt_FOA/files/header.html foa.html ./../roles/bvt_FOA/files/footer.html > BVT_FOA.html
      delegate_to: localhost

    - name: "Copy files to consolidated results directory"
      copy:
        src: "{{ item }}"
        dest: "{{ results_dir }}/BVT_FOA/"
        owner: root
        group: root
        mode: '644'
      delegate_to: 'localhost'
      with_items:
        -  "{{ playbook_dir }}/results_bvt/BVT_FOA.html"
        -  "{{ playbook_dir }}/results_bvt/bvt_result"
    
    - name: "Clear temporary Files on Ansible Controller"
      shell: |
         cd "{{ playbook_dir }}"
         rm -rf results_bvt
      delegate_to: localhost
    
    - name: "Remove temporary directory on target server"
      file:
          path: "{{ fanoutagent_shared_volume }}/Automation"
          state: absent

...
