---
# tasks file for download_iso

- name: 'Clean Temporary Directory on Source Server for ansible'
  file:
      path: "{{ build_src_location }}"
      state: absent
      mode: '644'
  delegate_to: 'localhost'
  notify: handler_for_message - temp_dir_src
  tags: temp_dir_src

- name: 'Create Temporary Directory on Source Server for ansible'
  file:
      path: "{{ build_src_location }}"
      state: directory
      mode: '644'
  delegate_to: 'localhost'
  notify: handler_for_message - temp_dir_src
  tags: temp_dir_src


#- name: 'Check if {{ idm_48x_tar_name }} exists locally'
#  stat:
#      path: '{{ build_src_location }}/{{ idm_48_tar_name }}'
#  delegate_to: 'localhost'
#  register: register_local_iso
#  notify: handler_for_message - check_iso_locally
#  tags: check_iso_locally

- name: "Download {{ product_version }} build locally"
  get_url:
      dest: "{{ build_src_location }}/{{ idm_48_tar_name }}"
      url: "{{ idm_48_tar_url }}/{{ idm_48_tar_name }}"
      validate_certs: false
  delegate_to: 'localhost'
  notify: handler_for_message - build_download
#  when: not register_local_iso.stat.exists
  tags: build_download
  
- name: "Un-archive {{ idm_48_tar_name }} "
  shell: tar -zxvf "{{ build_src_location }}/{{ idm_48_tar_name }}"
  args:  
    chdir: "{{ build_src_location }}"
  delegate_to: 'localhost'
#  notify: handler_for_message - build_download
  tags: build_download

- name: "Remove {{ idm_48_tar_name }}"
  file:
    state: absent
    path: "{{ build_src_location }}/{{ idm_48_tar_name }}"

# Download service pack
# - name: "Download md5sum File"
#   get_url:
#       dest: "{{ role_path }}/files/"
#       url: "{{ service_pack_iso_url }}/{{ service_pack_iso_name }}.md5"
#   delegate_to: localhost

# - name: "Read md5sum of the build to be downloaded"
#   shell: |
#       cat "{{ role_path }}/files/{{ service_pack_iso_name }}.md5" | awk '{ print $1 }'
#   register: md5sum_latest
#   delegate_to: localhost

# - name: "Update md5sum value to latest"
#   lineinfile:
#         path:  "{{ playbook_dir }}/roles/download_iso/defaults/main.yml"
#         regexp: '^service_pack_iso_md5sum:'
#         line: 'service_pack_iso_md5sum: {{md5sum_latest.stdout}}'
#   when: md5sum_latest.stdout != service_pack_iso_md5sum
#   delegate_to: localhost

# - name: "Remove Previous ISO if md5sum don't match"
#   file:
#     path:  "{{ build_src_location }}/{{ service_pack_iso_name }}"
#     state: absent
#   when: md5sum_latest.stdout != service_pack_iso_md5sum
#   delegate_to: localhost

- name: 'Clean Temporary Directory on Source Server for ansible'
  file:
      path: "{{ results_dir }}"
      state: absent
      mode: '644'
  delegate_to: 'localhost'
  tags: temp_dir_rpt
  
... 
