{{- if (include "identity-manager.identityengine.deploy" .) }}

{{- if .Values.identityengine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.identityengine.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.identityengine.labels" . | nindent 4 }}
  {{- with .Values.identityengine.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 

{{- end }}
