{{- if (include "identity-manager.osp.deploy" .) }}

{{- if .Values.osp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.osp.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.osp.labels" . | nindent 4 }}
  {{- with .Values.osp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
