---
# tasks file for xpoz_engine
    - name: "Copy XPOZ_ENV.txt to XPOZ Server"
      win_copy:
         src: XPOZ_ENV.TXT
         dest: C:\CICD_pipeline\stage1_engine\XPOZv61_20080728-W\
         backup: yes
  
    - name: "Remove temporary console file(if present)"
      win_file:
          path: C:\CICD_pipeline\stage1_engine\console.txt
          state: absent

    - name: "Run XPOZ for IDM Engine"
      win_shell: .\XPOZConsole.exe C:\CICD_pipeline\stage1_engine\Engine\Engine.env >>C:\CICD_pipeline\stage1_engine\console.txt
      args:
           chdir: C:\CICD_pipeline\stage1_engine\XPOZv61_20080728-W
      ignore_errors: true

    - name: "Fetch files from XPOZ Server to Ansible Controller"
      fetch:
        src: "{{ item }}"
        dest: "{{ results_dir }}/Regression_Engine/"
        flat: yes
      with_items:
          - "C:\\CICD_pipeline\\stage1_engine\\console.txt"
          - "C:\\CICD_pipeline\\stage1_engine\\Engine\\ENGINE.html"
          - "C:\\CICD_pipeline\\stage1_engine\\Engine\\ENGINE_tc.html"
          - "C:\\CICD_pipeline\\stage1_engine\\Engine\\ENGINE_err.html"

    - name: "Register Test Results"
      shell: |
           dos2unix "{{ results_dir }}/Regression_Engine/console.txt"
           awk '/returned: 0/{flag=1; next} /!!! STOPPED !!!/{flag=0} flag' "{{ results_dir }}/Regression_Engine/console.txt" > "{{ results_dir }}/Regression_Engine/xpoz_result"
      delegate_to: 'localhost'

    - name: "Delete temporary XPOZ ENV File"
      file:
         path: "{{ role_path }}/files/XPOZ_ENV.TXT"
         state: absent
      delegate_to: localhost

...
