{{- if (include "identity-manager.sspr.deploy" .) }}

{{- if .Values.sspr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.sspr.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.sspr.labels" . | nindent 4 }}
  {{- with .Values.sspr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 

{{- end }}
