---
##Play to run BVT on IDM Engine
- name: "Run BVT on IDM Engine and Share Results"
  hosts: idmengine
  become: yes
  become_method: sudo
  vars_files:
  - ../../variables/versions.yml
  roles:
  - role: bvt_engine
    when: "groups[ 'idmengine' ] | length > 0"
  tags: run_bvt_engine
  
#Play to run XPOZ Automation
- name: 'Run XPOZ Automation on IDM Engine and Share Results'
  hosts: xpoz_server
  roles:
    - role:                     variables_idm
      when:                     false
    - role:                     xpoz_engine
      when:                     "groups[ 'idmengine' ] | length > 0 and groups[ 'xpoz_server' ] | length > 0"
  tags: run_xpoz_engine
    

...
