{{- if (include "identity-manager.activemq.deploy" .) }}

{{- if .Values.activemq.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.activemq.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.activemq.labels" . | nindent 4 }}
  {{- with .Values.activemq.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 

{{- end }}
