---
# tasks file for bvt_rl

    - name: "Create Automation Directory for BVT"
      file:
          path: "/tmp/Automation"
          state: directory
          mode: '644'
          
    - name: "Copy Version Check script to Automation Directory"
      template:
           src: "bvt_rl.sh"
           dest: "/tmp/Automation"
           owner: root
           group: root
           mode: '777'
           
    - name: "Creates results Directory"
      file:
        path: "{{ playbook_dir}}/results_bvt"
        state: directory
        mode: '644'
      delegate_to: localhost
        
    - name: "Run Version Check Script on BVT IDM FOA"
      shell: |
          cd /tmp/Automation
          sh bvt_rl.sh
    
 
    - name: "Fetch log files from BVT RL to Ansible Controller"
      fetch:
        src: "{{ item }}"
        dest: "{{ playbook_dir}}/results_bvt/"
        flat: yes
      with_items:
             - /tmp/Automation/result
             - /tmp/Automation/rl.html
             - /tmp/Automation/bvt_result
      
    - name: "Read version check results"
      shell: |
          cat "{{ playbook_dir}}/results_bvt/result"
      register: results
      delegate_to: localhost
      

    - name: "Generate Remote loader jars version check html report"
      shell: |
          cd "{{ playbook_dir }}/results_bvt"
          cat ./../roles/bvt_rl/files/header.html rl.html ./../roles/bvt_rl/files/footer.html > BVT_RL.html
      delegate_to: localhost

    - name: "Copy files for consolidation"
      copy:
        src: "{{ item }}"
        dest: "{{ results_dir }}/BVT_RL/"
        owner: root
        group: root
        mode: '644'
      delegate_to: 'localhost'
      with_items:
        -  "{{ playbook_dir }}/results_bvt/BVT_RL.html"
        -  "{{ playbook_dir }}/results_bvt/bvt_result"
      delegate_to: 'localhost'
    
    - name: "Clear temporary Files on Ansible Controller"
      shell: |
         cd "{{ playbook_dir }}"
         rm -rf results_bvt
      delegate_to: localhost
    
    - name: "Remove temporary directory on target server"
      file:
          path: "/tmp/Automation"
          state: absent

...
