apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-deployment-data
data:
  HELM_CHART_RELEASE_NAME: {{ .Release.Name | quote }}
  HELM_CHART_VERSION: {{ .Chart.Version | quote }}
  HELM_CHART_APPLICATION_VERSION: {{ .Chart.AppVersion | quote }}
  {{- if .Values.identityengine.deploy }}
  ENGINE_REPLICA_COUNT: {{ .Values.identityengine.replicaCount | quote }}
  {{- end }}
  {{- if (include "identity-manager.osp.deploy" .) }}
  OSP_REPLICA_COUNT: {{ .Values.osp.replicaCount | quote }}
  {{- end }}
  {{- if (include "identity-manager.identityapplications.deploy" .) }}
  UA_REPLICA_COUNT: {{ .Values.identityapplications.replicaCount | quote }}
  {{- end }}
 
