apiVersion: v1
kind: Secret
metadata:
  name: "identity-manager-key-store-pwd"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "identity-manager-key-store-pwd") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $keystore-pwd to existing secret data or generate a random one when not exists
  {{- $keystorePwd := (get $secretData "keystore-pwd") | default (randAlphaNum 32 | b64enc) }}
  keystore-pwd: {{ $keystorePwd | quote }}
