

{{- if .Values.secret_manager.azureKeyVault.use -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secret-provider-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secret_manager.azureKeyVault.azureUserAssignedIdentityID }}
    keyvaultName: {{ .Values.secret_manager.azureKeyVault.azureKeyVaultName }}
    cloudName: ""
    objects:  |
      array:
        {{- $secretList := include "identity-manager.configuration.secrets.list" .Values }}
        {{- range $secretList | fromYamlArray | uniq }}
        - |
          objectName: {{ . }}
          objectType: secret
          objectVersion: ""
        {{- end }}
    tenantId: {{ .Values.secret_manager.azureKeyVault.azureKeyVaultTenantId }}
{{- end }}

---

{{- if .Values.secret_manager.azureKeyVault.use -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-ingress-tls-certificate-key-provider-class
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: {{ .Release.Name }}-ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: {{ .Values.ingress.tls.azureKeyVaultCertificateName }}
      key: tls.key
    - objectName: {{ .Values.ingress.tls.azureKeyVaultCertificateName }}
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secret_manager.azureKeyVault.azureUserAssignedIdentityID }}
    keyvaultName: {{ .Values.secret_manager.azureKeyVault.azureKeyVaultName }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: {{ .Values.ingress.tls.azureKeyVaultCertificateName }}
          objectType: secret
    tenantId: {{ .Values.secret_manager.azureKeyVault.azureKeyVaultTenantId }}
{{- end }}

