---
#Play to run BVT for Identity reporting
- name: "Run BVT for Identity reporting and Share Results"
  hosts: idmengine
  become: yes
  become_method: sudo
  vars_files:
    - ../../versions/vars.yml
  roles:
    - role: bvt_reporting
      when: "groups[ 'idmengine' ] | length > 0"
  tags: run_bvt_engine
  
#Play to run Rest API Automation
- name: 'Run Rest API Automation on Identity reporting and Share Results'
  hosts: mvn_server
  roles:
  - role:                     variables_idm
    when:                     false
  - role:                     restauto_reporting
    when:                     "groups[ 'mvn_server' ] | length > 0"
  tags: run_restapi_auto
    
#Play to remove temporary result directories
- name: 'Remove temporary result directories'
  hosts: control
  tasks:
  - name: "Remove bvt result directory"
    file:
      path: "./results_bvt"
      state: absent
  tags: remove_results_dir
...
