apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rl
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "remoteloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - port: {{ $port }}
      targetPort: port-{{ $port }}
      protocol: TCP
      name: port-{{ $port }}
  {{- end }}
  selector:
    {{- include "remoteloader.selectorLabels" . | nindent 4 }}
