{{- if (include "identity-manager.identityreporting.deploy" .) }}

{{- if .Values.identityreporting.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.identityreporting.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.identityreporting.labels" . | nindent 4 }}
  {{- with .Values.identityreporting.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
