{{- if (include "identity-manager.identityapplications.deploy" .) }}

{{- if .Values.identityapplications.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.identityapplications.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.identityapplications.labels" . | nindent 4 }}
  {{- with .Values.identityapplications.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
