{{- if (include "identity-manager.identityapplications.deploy" .) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-manager.identityapplications.name" . }}
  annotations:
    {{- toYaml .Values.identityapplications.service.annotations | nindent 4 }}
  labels:
    {{- include "identity-manager.identityapplications.labels" . | nindent 4 }}
spec:
  type: {{ .Values.identityapplications.service.type }}
  ports:
    - port: {{ .Values.identityapplications.service.ports.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "identity-manager.identityapplications.selectorLabels" . | nindent 4 }}

{{- end }}
