---
## tasks file for install_IDC


    - name: "Set timezone to Asia/Kolkata"
      timezone:
        name: Asia/Kolkata
      
    - name: "Stop and disable firewall service"
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      register: firewall_status
      failed_when: firewall_status is failed and "Could not find the requested service firewalld" not in firewall_status.msg
    
    - name: "Get hostname"
      shell: echo $HOSTNAME
      register: fqdn
      
    - name: "Set IDC_host variables values"
      set_fact:
        IDC_host: "{{ fqdn.stdout | lower }}"
        
    - name: "Create Temporary Directory on Target Server for ansible"
      file:
          path: "{{ build_dest_location }}"
          state: directory
          mode: '644'
#      notify: handler_for_message - temp_dir_target
      tags: temp_dir_target

    - name: "Download {{ service_pack_tar_name }}  on IDC"
      get_url:
          dest: "{{ build_dest_location }}"
          url: "{{ service_pack_tar_url }}/{{ service_pack_tar_name }}.tar.gz"
#      notify: handler_for_message - build_download
      tags: build_download
      
    - name: "Un-archive {{ service_pack_tar_name }} "
      unarchive:
        remote_src: yes
        src: "{{ build_dest_location }}/{{ service_pack_tar_name }}.tar.gz"
        dest: "{{ build_dest_location }}"
        mode: 0755
#      notify: handler_for_message - build_download
      tags: build_download
            
    - name: "Install pexpect package required for silent install of IDC"
      pip:
        name: pexpect
        version: 4.8.0
        
    - name: "Copy silent install code to IDC Server"
      template:
        src: "{{ silent_install_IDC }}"
        dest: "{{ build_dest_location }}/{{ service_pack_tar_name }}"
        owner: root
        group: root
        mode: '755'
        
    - name: "Copy IDC required certificates to IDC Server"
      copy:
        src: "{{ item }}"
        dest: "{{ build_dest_location }}/{{ service_pack_tar_name }}"
        owner: root
        group: root
        mode: '755'
      with_items:
        - SSCert.pem
        - cert.pfx
              
    - name: "Run pexpect for IDC installation"
      shell: python3.6 {{ silent_install_IDC }}
      args:
           chdir: "{{ build_dest_location }}/{{ service_pack_tar_name }}"
      ignore_errors: true
      

    - name: "Clean-Up redundant files on Target Server"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ build_dest_location }}/{{ service_pack_tar_name }}/{{ silent_install_IDC }}"
        - "{{ build_dest_location }}/{{ service_pack_tar_name }}.tar.gz"


      
           
      
      

      
