---
# tasks file for consolidated_report

    - name: "Download Build Number"
      uri: url="{{ idm_485_build_number }}" return_content="yes"
      register: idm_build_no
      delegate_to: localhost
      
    - name: "Copy Version Check script to Automation Directory"
      template:
           src: "bvt_results.sh"
           dest: "{{ role_path }}/files/bvt_results.sh"
           owner: root
           group: root
           mode: '777'
      delegate_to: localhost
           
    - name: "Copy Version Check script to Automation Directory"
      template:
           src: "xpoz_results.sh"
           dest: "{{ role_path }}/files/xpoz_results.sh"
           owner: root
           group: root
           mode: '777'
      delegate_to: localhost
    
    - name: "Generate BVT Consolidated report"
      shell: sh "{{ role_path }}/files/bvt_results.sh"
      delegate_to: localhost
      
    - name: "Generate XPOZ Consolidated report"
      shell: sh "{{ role_path }}/files/xpoz_results.sh"
      delegate_to: localhost
      
    - name: "Read header body and footer file"
      shell: |
        cat "{{ role_path }}/files/header.html" > "{{ results_dir }}/consolidated_BVT.html"
        cat "{{ role_path }}/files/header.html" > "{{ results_dir }}/consolidated_XPOZ.html"


        echo "<p>Hi All,</p>
              <p>Please find the executive summary of the Build Validation Test Results performed</p>
                <span id=generated>Generated from build no : {{ idm_build_no.content }}</span>" >> "{{ results_dir }}/consolidated_BVT.html"
        echo "<p>Hi All,</p>
              <p>Please find the executive summary of the Regression Testing Results performed</p>
                <span id=generated>Generated from build no : {{ idm_build_no.content }}</span>" >> "{{ results_dir }}/consolidated_XPOZ.html"
        cat "{{ results_dir }}/consolidated_BVT_pre.html" >> "{{ results_dir }}/consolidated_BVT.html"
        cat "{{ results_dir }}/consolidated_XPOZ_pre.html" >> "{{ results_dir }}/consolidated_XPOZ.html"      
               
        echo "<p> For detailed logs , <a href="{{ BUILD_URL }}">Refer here</a> </p>" >> "{{ results_dir }}/consolidated_BVT.html"
        echo "<p> For detailed logs , <a href="{{ BUILD_URL }}">Refer here</a> </p>" >> "{{ results_dir }}/consolidated_XPOZ.html"
        echo "<p>Please find the Allure report in below links:</p>" >> "{{ results_dir }}/consolidated_XPOZ.html"
        echo "<p> <a href="{{ BUILD_URL }}/Regression_Reporting/allure-report/index.html">Identity Reporting</a> </p>" >> "{{ results_dir }}/consolidated_XPOZ.html"
        echo "<p> <a href="{{ BUILD_URL }}/Regression_IDConsole/allure-report/index.html">Identity Console</a> </p>" >> "{{ results_dir }}/consolidated_XPOZ.html"
        
        cat "{{ role_path }}/files/footer.html" >> "{{ results_dir }}/consolidated_BVT.html"
        cat "{{ role_path }}/files/footer.html" >> "{{ results_dir }}/consolidated_XPOZ.html"   
        
        rm -rf "{{ results_dir }}/consolidated_BVT_pre.html" "{{ results_dir }}/consolidated_XPOZ_pre.html"
      delegate_to: localhost

    - name: "Register the BVT results"
      shell: cat "{{ results_dir }}/consolidated_BVT.html"
      register: results_bvt
      delegate_to: localhost
      
    - name: "Register the XPOZ results"
      shell: cat "{{ results_dir }}/consolidated_XPOZ.html"
      register: results_xpoz
      delegate_to: localhost

    - name: "Send e-mail to Stakeholders for BVT report"
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        subject: 'IDM 485 Containers - Build {{ idm_build_no.content }}: Build Validation Test results'
        body: |              
                {{ results_bvt.stdout }}

        from: "{{ from_user }}"
#        to: DL-BLR IDMApps QA <DL-BLR-IDMApps-QA@microfocus.com>, DL-BLR IDMSE QA <DL-BLR-IDMSE-QA@microfocus.com>, DL-BLR IDM CORE <DL-BLR-IDM-CORE@microfocus.com>, Virendra Parmar <Virendra.Parmar@microfocus.com>
        to:  Shanmukh Pawan <shanmukhpawan.moparthi@microfocus.com>, Rajat Kalsotra <Rajat.Kalsotra@microfocus.com>
        subtype: html
#        attach:
#         -  "{{ results_dir }}/BVT_Engine/BVT_Drivers.html"
#         -  "{{ results_dir }}/BVT_Engine/BVT_ThirdPartyJars_Engine.html"
#         -  "{{ results_dir }}/BVT_RL/BVT_RL.html"
#         -  "{{ results_dir }}/BVT_FOA/BVT_FOA.html"
#         -  "{{ results_dir }}/BVT_Reporting/BVT_Reporting.html"
      delegate_to: 'localhost'
      
      
      
    - name: "Send e-mail to Stakeholders for Regression report"
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ username }}"
        password: "{{ password }}"
        subject: 'IDM 485 Containers - Build {{ idm_build_no.content }}: Regression Suite Testing results'
        body: |               
                {{ results_xpoz.stdout }}

        from: "{{ from_user }}"
#        to: DL-BLR IDMApps QA <DL-BLR-IDMApps-QA@microfocus.com>, DL-BLR IDMSE QA <DL-BLR-IDMSE-QA@microfocus.com>, DL-BLR IDM CORE <DL-BLR-IDM-CORE@microfocus.com>, Virendra Parmar <Virendra.Parmar@microfocus.com>
        to:  Shanmukh Pawan <shanmukhpawan.moparthi@microfocus.com>, Rajat Kalsotra <Rajat.Kalsotra@microfocus.com>
        subtype: html       
      delegate_to: 'localhost'