{{- if (include "identity-manager.identityconsole.deploy" .) }}

{{- if .Values.identityconsole.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-manager.identityconsole.serviceAccountName" . }}
  labels:
    {{- include "identity-manager.identityconsole.labels" . | nindent 4 }}
  {{- with .Values.identityconsole.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
