---
# tasks file for formrenderer

- name : Get the Form Renderer image file stats
  local_action: stat path="{{ playbook_dir | dirname }}/docker-images/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_formrenderer.tar.gz"
  register: frfile

- name : Check for image existence in Docker host
  shell : docker images | grep formrenderer | grep {{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}
  register : imagealreadyloaded
  ignore_errors : yes

- name : Copy the Form Renderer image to Docker host
  copy :
          src : "{{ playbook_dir | dirname }}/docker-images/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_formrenderer.tar.gz"
          dest : "{{ formrenderer_shared_volume }}"
  when : 
        - frfile.stat.exists
        - imagealreadyloaded.rc == 1

- name : Load the Form Renderer image
  docker_image:
    state : present
    name: formrenderer:idm-{{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}
    load_path: "{{ formrenderer_shared_volume }}/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_formrenderer.tar.gz"
    timeout: 3000
    source: load
  register : formrendererLoadImage
  notify : Load Form Renderer image
  when : imagealreadyloaded.rc == 1

- name : Copy silent.properties file to target server
  copy :
    src : "{{ playbook_dir }}/roles/variables/files/silent.properties"
    dest : "{{ formrenderer_shared_volume }}" 
    
- name : Copy Form Renderer files to shared volume
  copy :
    src : "{{ playbook_dir }}/input/{{ item }}"
    dest : "{{ formrenderer_shared_volume }}"
  loop: "{{ formrenderer_files }}"
  when: formrenderer_files is defined
  
- name : Deploy Form Renderer container
  docker_container :
    name : "{{ formrenderer_container_name }}"
    image : formrenderer:idm-{{marketing_major}}.{{marketing_minor}}.{{marketing_revision}}
    network_mode : "{{ network_set }}"
    networks :
      - name : "{{ network_set }}"
        ipv4_address : "{{ formrenderer_container_ipaddress }}"
    state: started
    stop_timeout: 300
    hostname : "{{ FR_SERVER_HOST }}"
    volumes : "{{ formrenderer_volumes | default([]) }}"
    ports : "{{ formrenderer_port_mapping | default([]) }}"
    dns_servers : "{{ dns_list | default([]) }}"
    env:
      SILENT_INSTALL_FILE : /config/silent.properties
  tags : deploy_fr_container
  notify : Deploy Form Renderer Container
  
# Wait for 60 seconds for the container to up and running.
- pause:
    seconds : 60

- name : Delete Form Renderer tarball
  file :
          path : "{{ formrenderer_shared_volume }}/IDM_{{marketing_major}}{{marketing_minor}}{{marketing_revision}}_formrenderer.tar.gz"
          state : absent
          
- name: Delete silent.properties file
  file:
    path: "{{ formrenderer_shared_volume }}/silent.properties"
    state: absent


