---
# handlers file for idmengine
    - name: handler_for_message - check_iso_locally
      debug:
        msg: "{{ idm_48_iso_name }} is available on Control Server"

    - name: handler_for_message - temp_dir_target
      debug:
        msg: Temp directory is created on Target Server

    - name: handler_for_message - copy_iso_to_target
      debug:
        msg: "{{ idm_48_iso_name }} is copied to Target Server"

    - name: handler_for_message - build_download
      debug:
        msg: Build Downloaded Successfully

    - name: handler_for_message - umount_iso_if_present
      debug:
        msg: "Previous ISO has been unmounted"

    - name: handler_for_message - build_mount
      debug:
        msg: Build Mounted Successfully

    - name: handler_for_message - copy_engine_silent_prop
      debug:
        msg: Copied Engine Silent Properties file to IDM Engine Server

    - name: handler_for_message - copy_custom_driverset_ldif
      debug:
        msg: Copied Custom Driverset ldif file to IDM Engine Server

    - name: handler_for_message - install_engine
      debug:
        msg: Installed IDM Engine on Target Server Successfully

    - name: handler_for_message - configure_engine
      debug:
        msg: Configured IDM Engine on Target Server Successfully

    - name: handler_for_task - remove_property_file
      file:
        path: "{{ build_dest_location}}/{{ silent_prop_engine }}"
        state: absent
    
...
